"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 3.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import sys

from django.core.management.utils import get_random_secret_key

from backend.canvas_scopes import DEFAULT_CANVAS_SCOPES


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

PROJECT_ROOT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), ".."),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', get_random_secret_key())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", 'false').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'backend.canvas_app_explorer',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'webpack_loader',
    'rest_framework',
    'pylti1p3.contrib.django.lti1p3_tool_config',
    'tinymce',
    'canvas_oauth.apps.CanvasOAuthConfig',
    'drf_spectacular',
    'watchman',
    'rest_framework_tracking',
    'django_q',
    'constance',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'canvas_oauth.middleware.OAuthMiddleware',
    'csp.middleware.CSPMiddleware'
]

MIGRATION_MODULES = {
    'canvas_oauth': 'backend.canvas_oauth.migrations',
}

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'backend.canvas_app_explorer.context_processors.cae_globals'
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'canvas_app_explorer_local'),
        'USER': os.getenv('DB_USER', 'cae_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'cae_pw'),
        'HOST': os.getenv('DB_HOST', 'instructor_tools_mysql'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4'},
        'TEST': {
            'NAME': 'test_it',
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_unicode_ci'
        }
    }
}

TEST_RUNNER = 'backend.tests.test_setup.CustomTestRunner'


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'frontend'),
)

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')

WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'frontend/webpack-stats.json')
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

DEFAULT_FILE_STORAGE = 'backend.canvas_app_explorer.storage_get_file.DatabaseFileStorage'


# So request works over the proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

DB_CACHE_CONFIGS = os.getenv(
    'DB_CACHE_CONFIGS',
    {
        'CACHE_TTL': 600,
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
        'CACHE_KEY_PREFIX': 'app_explorer',
        'CACHE_OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PASSWORD': os.getenv('REDIS_PASS')
        }
    }
)

CACHES = {
    'default': {
        'BACKEND': DB_CACHE_CONFIGS['BACKEND'],
        'LOCATION': DB_CACHE_CONFIGS['LOCATION'],
        'OPTIONS': DB_CACHE_CONFIGS['CACHE_OPTIONS'],
        "KEY_PREFIX": DB_CACHE_CONFIGS['CACHE_KEY_PREFIX'],
        "TIMEOUT": DB_CACHE_CONFIGS['CACHE_TTL']
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    # Gunicorns logging format https://github.com/benoitc/gunicorn/blob/19.x/gunicorn/glogging.py
    'formatters': {
        "generic": {
            "format": "%(asctime)s [%(levelname)s] [%(filename)s:%(lineno)d] %(message)s",
            "datefmt": "[%Y-%m-%d %H:%M:%S %z]",
            "class": "logging.Formatter",
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'generic',
        },
    },
    'root': {
        'level': os.getenv('ROOT_LOG_LEVEL', 'INFO'),
        'handlers': ['console']
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'propagate': False,
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'canvas_oauth': {
            'handlers': ['console'],
            'level': 'WARN'
        },
        'rest_framework_tracking': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },# ...existing code...
        'django.db.backends': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    }
}

DRF_TRACKING_LOGGING = {
    'LOGGING_METHODS': ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'],
    'SENSITIVE_FIELDS': {'password', 'token', 'access_token'},
    'DATABASE_LOGGING': True,  # Enable database logging explicitly
}

TINYMCE_DEFAULT_CONFIG = {
    'menubar': True,
    "plugins": "advlist,autolink,code,lists,link,anchor,insertdatetime,media,table,paste,wordcount",
    "toolbar": "bold italic backcolor | "
        "bullist numlist outdent indent | removeformat | code | help",
    "default_link_target": "_blank",
    "invalid_elements": "h1, h2, h3, h4, h5, h6",
    "invalid_styles": "color, font-family, background-color, line-height",
    "promotion": False,

    "style_formats": [
        { 
            "title": 'Inline', 
            "items": [
                { "title": 'Bold', "format": 'bold' },
                { "title": 'Italic', "format": 'italic' },
                { "title": 'Underline', "format": 'underline' },
                { "title": 'Strikethrough', "format": 'strikethrough' },
                { "title": 'Superscript', "format": 'superscript' },
                { "title": 'Subscript', "format": 'subscript' },
                { "title": 'Code', "format": 'code' }
            ]
        },
        { 
            "title": 'Blocks',  
            "items": [
                { "title": 'Paragraph', "format": 'p' },
                { "title": 'Blockquote', "format": 'blockquote' },
                { "title": 'Div', "format": 'div' },
                { "title": 'Pre', "format": 'pre' }
            ]
        },
        { 
            "title": 'Align',  
            "items": [
                { "title": 'Left', "format": 'alignleft' },
                { "title": 'Center', "format": 'aligncenter' },
                { "title": 'Right', "format": 'alignright' },
                { "title": 'Justify', "format": 'alignjustify' }
            ]
        }
    ],
    "block_formats": "Paragraph=p",
    "removed_menuitems": "fontformats fontsizes lineheight forecolor backcolor",
}

# Watchman settings (https://github.com/mwarkentin/django-watchman)
WATCHMAN_TOKENS = os.getenv('DJANGO_WATCHMAN_TOKENS', None)
WATCHMAN_TOKEN_NAME = os.getenv('DJANGO_WATCHMAN_TOKEN_NAME', 'cae-watchman-token')
WATCHMAN_CHECKS = ('watchman.checks.caches', 'watchman.checks.databases')

# OAuth Settings, get these from the environment
# TODO: Add some of these to the Django LTI model
CANVAS_OAUTH_CLIENT_ID = os.getenv('CANVAS_OAUTH_CLIENT_ID', 'canvas_app_explorer')
CANVAS_OAUTH_CLIENT_SECRET = os.getenv('CANVAS_OAUTH_CLIENT_SECRET', 'canvas_app_explorer')
CANVAS_OAUTH_CANVAS_DOMAIN = os.getenv('CANVAS_OAUTH_CANVAS_DOMAIN', 'canvas.instructure.com')

# Scopes environment variable provides a way to recover if Canvas changes scope identifiers.
if isinstance((env_canvas_scopes := os.getenv('CANVAS_OAUTH_SCOPES')), str):
    CANVAS_OAUTH_SCOPES = env_canvas_scopes.split(',')
else:
    CANVAS_OAUTH_SCOPES = DEFAULT_CANVAS_SCOPES

CANVAS_OAUTH_TOKEN_EXPIRATION_BUFFER = os.getenv('CANVAS_OAUTH_TOKEN_EXPIRATION_BUFFER', timedelta(minutes=15))
CANVAS_OAUTH_ERROR_TEMPLATE = os.getenv('CANVAS_OAUTH_ERROR_TEMPLATE', 'canvas_app_explorer/oauth_error.html')

# These are mostly needed by Canvas but it should also be on in general
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", False)
if CSRF_COOKIE_SECURE:
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", [])
    SESSION_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Enables Proxies that set headers
    USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', True)

# Set CSP_FRAME_SRC to the your Canvas domains
CSP_FRAME_ANCESTORS = ["'self'",] + os.getenv('CSP_FRAME_ANCESTORS', '').split(',')
# This is currently unsafe-inline because of PyLTI scripts. This may be fixed in the future.
CSP_SCRIPT_SRC = ["'self'", "https:", "'unsafe-inline'",]
CSP_CONNECT_SRC = ["'self'", ] + os.getenv('CSP_CONNECT_SRC', '').split(',')
CSP_IMG_SRC = ["'self'", "data:"] + os.getenv('CSP_IMG_SRC', '').split(',') 

# Allow inline styles. There are a few styles that come up in the report so it seems easier to just allow unsafe-inline here.
CSP_STYLE_SRC = ["'self'", "https:", "'unsafe-inline'"]

SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", 'None')
CSRF_COOKIE_SAMESITE = os.getenv("CSRF_COOKIE_SAMESITE", 'None')

LTI_CONFIG_DISABLE_DEPLOYMENT_ID_VALIDATION = os.getenv('LTI_CONFIG_DISABLE_DEPLOYMENT_ID_VALIDATION', False)
RANDOM_PASSWORD_DEFAULT_LENGTH = os.getenv('RANDOM_PASSWORD_DEFAULT_LENGTH', 32)

# DRF, Spectacular, etc.
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
    'EXCEPTION_HANDLER': 'backend.canvas_app_explorer.utils.custom_exception_handler'
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Canvas App Explorer API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

TEST_API_KEY = os.getenv('TEST_API_KEY', '')
TEST_API_URL = os.getenv('TEST_API_URL', '')
TEST_COURSE_ID = os.getenv('TEST_COURSE_ID', 1)

# U-M Consent Manager & Google Analytics tracking
GOOGLE_ANALYTICS_ID = os.getenv('GOOGLE_ANALYTICS_ID', '')
UM_CONSENT_MANAGER_SCRIPT_DOMAIN = os.getenv('UM_CONSENT_MANAGER_SCRIPT_DOMAIN', 'https://umich.edu/apis/umconsentmanager/consentmanager.js')

#Django Q2 using default Django ORM
Q_CLUSTER = {
    'name': os.getenv('Q_CLUSTER_NAME', 'IT_Cluster'),
    'workers': int(os.getenv('Q_CLUSTER_WORKERS', 4)),
    'timeout': int(os.getenv('Q_CLUSTER_TIMEOUT', 1800)), # 30 minutes
    'retry': int(os.getenv('Q_CLUSTER_RETRY', 3600)), # 1hr
    'bulk': int(os.getenv('Q_CLUSTER_BULK', 5)),
    'max_attempts': int(os.getenv('Q_CLUSTER_MAX_ATTEMPTS', 1)),
    'orm': 'default'
}

# Constance configuration for dynamic settings
CONSTANCE_CONFIG = {
    'AZURE_API_KEY': (
        os.getenv('AZURE_API_KEY', ''),
        'Azure OpenAI API Key'
    ),
    'AZURE_API_VERSION': (
        os.getenv('AZURE_API_VERSION', '2025-04-01-preview'),
        'Azure OpenAI API Version'
    ),
    'AZURE_API_BASE': (
        os.getenv('AZURE_API_BASE', 'https://api.umgpt.umich.edu/azure-openai-api'),
        'Azure OpenAI API Base URL'
    ),
    'AZURE_ORGANIZATION': (
        os.getenv('AZURE_ORGANIZATION', ''),
        'Azure Organization ID'
    ),
    'AZURE_MODEL': (
        os.getenv('AZURE_MODEL', 'gpt-4o'),
        'Azure OpenAI Model Name'
    ),
    'AZURE_ALT_TEXT_PROMPT': (
        os.getenv('AZURE_ALT_TEXT_PROMPT', """As an AI tool specialized in image recognition, generate concise and descriptive alt text for this image.
The description should be suitable for a student with a
vision impairment taking a quiz. Do not include phrases
like 'This is an image of...'. Provide only one concise
option with no further explanation.""").strip(),
        'Prompt for generating alt text'
    ),
    'AZURE_ALT_TEXT_TEMPERATURE': (
        float(os.getenv('AZURE_ALT_TEXT_TEMPERATURE', 0.0)),
        'Temperature for alt text generation: 0 = deterministic/consistent responses, 2 = maximum creativity/randomness'
    ),
    'IMAGE_MAX_DIMENSION': (
        int(os.getenv('IMAGE_MAX_DIMENSION', 512)),
        'Maximum dimension for image optimization (pixels)'
    ),
    'IMAGE_JPEG_QUALITY': (
        int(os.getenv('IMAGE_JPEG_QUALITY', 85)),
        'JPEG quality for image optimization (1-100)'
    ),
    'IMAGE_PROCESSING_CONCURRENCY': (
        int(os.getenv('IMAGE_PROCESSING_CONCURRENCY', 4)),
        'Number of concurrent image processing tasks (note: values over 4 were not tested and may timeout)'
    ),
    'HELP_URL': (
        os.getenv('HELP_URL', 'https://github.com/tl-its-umich-edu/canvas-app-explorer'),
        'URL for external help resource'
    ),
}

# Use in-memory backend for constance during tests to avoid database migration issues
if 'test' in sys.argv:
    CONSTANCE_BACKEND = 'constance.backends.memory.MemoryBackend'
else:
    CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'