# Generated by Django 3.2.14 on 2022-07-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canvasoauth2token',
            options={'verbose_name': 'Canvas OAuth2 Token', 'verbose_name_plural': 'Canvas OAuth2 Tokens'},
        ),
    ]
