# Generated by Django 4.2.23 on 2025-10-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0014_ltitool_launch_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='ltitool',
            name='tool_categories',
            field=models.ManyToManyField(to='canvas_app_explorer.toolcategory'),
        ),
    ]
