# Generated by Django 4.2.23 on 2025-10-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0015_toolcategory_ltitool_tool_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltitool',
            name='canvas_placement',
            field=models.ManyToManyField(blank=True, to='canvas_app_explorer.canvasplacement'),
        ),
        migrations.AlterField(
            model_name='ltitool',
            name='tool_categories',
            field=models.ManyToManyField(blank=True, to='canvas_app_explorer.toolcategory'),
        ),
    ]
