# Generated by Django 4.2.27 on 2025-12-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0015_contentitem_coursescan_imageitem_contentitem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='parent_quiz_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='quiz_assignment_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
