# Generated by Django 4.2.27 on 2025-12-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0017_alter_ltitool_canvas_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='content_parent_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('page', 'Page'), ('quiz', 'Quiz'), ('quiz question', 'Quiz Question')], max_length=20),
        ),
    ]
