# Generated by Django 4.2.27 on 2025-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0018_contentitem_content_parent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('page', 'Page'), ('quiz', 'Quiz'), ('quiz_question', 'Quiz Question')], max_length=20),
        ),
    ]
