# Generated by Django 4.2.27 on 2026-01-06 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0019_alter_contentitem_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='image_alt_text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)]),
        ),
    ]
