# Generated by Django 4.2.27 on 2026-01-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0020_imageitem_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
