# Generated by Django 4.2.27 on 2026-01-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0021_alter_imageitem_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='image_id',
        ),
    ]
