# Generated by Django 4.2.27 on 2026-01-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas_app_explorer', '0022_remove_imageitem_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
